name: Discord Bot CI

on:
  push:
    branches:
      - mind  # Change this to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Specify the Python version your bot requires

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # If you have a requirements.txt file

    - name: Run Bot
      run: python main.py  # Replace with the filename of your bot script
      env:
        TOKEN: ${{ secrets.TOKEN }}
